MEMORY
{
    ITCM      (wxa) : ORIGIN = 0x62FC0000, LENGTH = 20K
    DTCM      (wxa) : ORIGIN = 0x62FC5000, LENGTH = 4K
    XIP_FLASH (rwx) : ORIGIN = 0xA0000000, LENGTH = 128M
}

REGION_ALIAS("REGION_TEXT", XIP_FLASH);
REGION_ALIAS("REGION_RODATA", XIP_FLASH);
REGION_ALIAS("REGION_DATA", ITCM);
REGION_ALIAS("REGION_BSS", ITCM);
REGION_ALIAS("REGION_HEAP", DTCM);
REGION_ALIAS("REGION_STACK", DTCM);
